imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }

    - { resource: "@SyliusPayPalPlugin/Resources/config/config.yaml" }

parameters:
    fixtures_dir: "%kernel.project_dir%/src/Resources/fixtures"
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius.cache:
        type: array

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_api:
    enabled: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_ui:
    events:
        sylius.admin.login.form.content:
            blocks:
                test_credentials:
                    template: 'Admin/Security/Login/testCredentials.html.twig'
                    priority: 30

sylius_channel:
    resources:
        channel:
            classes:
                model: App\Entity\Channel\Channel

sylius_core:
    resources:
        channel_pricing:
            classes:
                model: App\Entity\Channel\ChannelPricing

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
