name: app

type: "php:7.2"

build:
    flavor: composer

relationships:
    database: "mysql:mysql"
    redis: "redis:redis"

runtime:
    extensions:
        - msgpack
        - igbinary
        - memcached
        - redis

dependencies:
    nodejs:
        yarn: "*"
        gulp-cli: "*"

web:
    locations:
        '/':
            root: "web"
            passthru: "/app.php"
            allow: true
            expires: -1
            scripts: true
        '/assets/shop':
            expires: 2w
            passthru: true
            allow: false
            rules:
                # Only allow static files from the assets directories.
                '\.(css|js|jpe?g|png|gif|svgz?|ico|bmp|tiff?|wbmp|ico|jng|bmp|html|pdf|otf|woff2|woff|eot|ttf|jar|swf|ogx|avi|wmv|asf|asx|mng|flv|webm|mov|ogv|mpe|mpe?g|mp4|3gpp|weba|ra|m4a|mp3|mp2|mpe?ga|midi?)$':
                    allow: true
        '/media/image':
            expires: 2w
            passthru: true
            allow: false
            rules:
                # Only allow static files from the assets directories.
                '\.(jpe?g|png|gif|svgz?)$':
                    allow: true
        '/media/cache/resolve':
            passthru: "/app.php"
            expires: -1
            allow: true
            scripts: true
        '/media/cache':
            expires: 2w
            passthru: true
            allow: false
            rules:
                # Only allow static files from the assets directories.
                '\.(jpe?g|png|gif|svgz?)$':
                    allow: true

disk: 4096

mounts:
    "/var/cache": "shared:files/cache"
    "/var/logs": "shared:files/logs"
    "/web/uploads": "shared:files/uploads"
    "/web/media": "shared:files/media"

hooks:
    build: |
        rm web/app_dev.php
        rm web/app_test.php
        rm web/app_test_cached.php
        rm -rf var/cache/*
        php bin/console --env=prod --no-debug --ansi cache:clear --no-warmup
        php bin/console --env=prod --no-debug --ansi cache:warmup
        php bin/console --env=prod --no-debug --ansi assets:install
        yarn install
        GULP_ENV=prod yarn build
    deploy: |
        rm -rf var/cache/*
        rm -rf var/media/*
        php bin/console --env=prod doctrine:migrations:migrate --no-interaction
        php bin/console --env=prod --no-debug sylius:fixtures:load

crons:
    reset:
        spec: "0 */1 * * *"
        cmd: "rm -rf web/media/* && php bin/console --env=prod --no-debug sylius:fixtures:load"
    renewcertificate:
        # Force a redeploy at 10 am (UTC) on the 3rd of every month.
        spec: '0 10 3 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi
