# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "config.yml" }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

swiftmailer:
    disable_delivery: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
