doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
