parameters:
    env(REDIS_HOST): ''
    env(REDIS_PORT): 0

doctrine:
    orm:
        metadata_cache_driver:
            type: "redis"
            database: 1
            host: "%env(resolve:REDIS_HOST)%"
            port: "%env(int:resolve:REDIS_PORT)%"
        query_cache_driver:
            type: "redis"
            database: 2
            host: "%env(resolve:REDIS_HOST)%"
            port: "%env(int:resolve:REDIS_PORT)%"
        result_cache_driver:
            type: "redis"
            database: 3
            host: "%env(resolve:REDIS_HOST)%"
            port: "%env(int:resolve:REDIS_PORT)%"
