doctrine:
    orm:
        metadata_cache_driver:
            type: "%metacache_driver%"
            database: 1
            host: "%redis_host%"
            port: "%redis_port%"
        query_cache_driver:
            type: "%querycache_driver%"
            database: 2
            host: "%redis_host%"
            port: "%redis_port%"
        result_cache_driver:
            type: "%resultcache_driver%"
            database: 3
            host: "%redis_host%"
            port: "%redis_port%"
