monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: rotating
        rotating:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
