# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    App\Generator\FlashMessageGeneratorInterface:
        class: App\Generator\VerificationFlashMessageGenerator
        arguments: ['@router', '@translator.default']

    App\Twig\LocaleExtension:
        class: App\Twig\LocaleExtension
        arguments: ['@Twig\Extra\Intl\IntlExtension']
        tags:
            - {name: twig.extension}
