# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    App\EventListener\AdminListener:
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: sylius.admin_user.pre_delete, method: preDelete }
            - { name: kernel.event_listener, event: sylius.admin_user.pre_update, method: preUpdate }

    App\EventListener\ChannelListener:
        arguments: ['@session', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request , method: preCreate }

    App\EventListener\UserRegistrationListener:
        class: App\EventListener\UserRegistrationListener
        arguments: ['@session', '@App\Generator\FlashMessageGeneratorInterface']
        tags:
            - { name: kernel.event_listener, event: sylius.user.email_verification.token , method: addVerificationLink }

    App\Generator\FlashMessageGeneratorInterface:
        class: App\Generator\VerificationFlashMessageGenerator
        arguments: ['@router', '@translator.default']

    App\Twig\LocaleExtension:
        class: App\Twig\LocaleExtension
        arguments: ['@Twig\Extra\Intl\IntlExtension']
        tags:
            - {name: twig.extension}

# Below services are added for support sylius 1.9, Remove it if will be fixed in vendors

    sylius_invoicing_plugin.generator.invoice_pdf_file:
        class: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        arguments:
            - "@twig"
            - "@knp_snappy.pdf"
            - "@file_locator"
            - "@@SyliusInvoicingPlugin/Invoice/Download/pdf.html.twig"
            - "@@SyliusInvoicingPlugin/Resources/assets/sylius-logo.png"

    Sylius\RefundPlugin\Generator\CreditMemoPdfFileGenerator:
        arguments:
            - "@sylius_refund.repository.credit_memo"
            - "@twig"
            - "@knp_snappy.pdf"
            - "@file_locator"
            - "@@SyliusRefundPlugin/Download/creditMemo.html.twig"
            - "@@SyliusRefundPlugin/Resources/assets/sylius-logo.png"

    sylius.sitemap_renderer.twig_adapter:
        class: SitemapPlugin\Renderer\TwigAdapter
        arguments:
            - "@twig"
            - "%sylius.sitemap_template%"
            - "%sylius.sitemap_absolute_url%"
            - "%sylius.sitemap_hreflang%"

    sylius.sitemap_index_renderer.twig_adapter:
        class: SitemapPlugin\Renderer\TwigAdapter
        arguments:
            - "@twig"
            - "%sylius.sitemap_index_template%"
            - "%sylius.sitemap_absolute_url%"
