# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    App\EventListener\AdminListener:
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: sylius.admin_user.pre_delete, method: preDelete }
            - { name: kernel.event_listener, event: sylius.admin_user.pre_update, method: preUpdate }

    App\EventListener\ChannelListener:
        arguments: ['@session', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request , method: preCreate }

    App\EventListener\UserRegistrationListener:
        class: App\EventListener\UserRegistrationListener
        arguments: ['@session', '@App\Generator\FlashMessageGeneratorInterface']
        tags:
            - { name: kernel.event_listener, event: sylius.user.email_verification.token , method: addVerificationLink }

    App\Generator\FlashMessageGeneratorInterface:
        class: App\Generator\VerificationFlashMessageGenerator
        arguments: ['@router', '@translator.default']

    App\Twig\LocaleExtension:
        class: App\Twig\LocaleExtension
        arguments: ['@Twig\Extra\Intl\IntlExtension']
        tags:
            - {name: twig.extension}

    bitbag_sylius_cms_plugin.twig.extension.block:
        class: App\Twig\RenderBlockExtension
        arguments:
            - "@bitbag_sylius_cms_plugin.repository.block"
            - "@bitbag_sylius_cms_plugin.resolver.block_resource"
            - "@twig"
        tags:
            - { name: twig.extension }

    bitbag_sylius_cms_plugin.twig.extension.product_pages:
        class: App\Twig\RenderProductPagesExtension
        arguments:
            - "@bitbag_sylius_cms_plugin.repository.page"
            - "@sylius.context.channel"
            - "@twig"
        tags:
            - { name: twig.extension }

    bitbag_sylius_cms_plugin.media_provider.image:
        class: App\MediaProvider\GenericProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/image.html.twig"
            - "media/image"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: image, label: bitbag_sylius_cms_plugin.ui.image_provider }

    bitbag_sylius_cms_plugin.media_provider.video:
        class: App\MediaProvider\GenericProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/video.html.twig"
            - "media/video"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: video, label: bitbag_sylius_cms_plugin.ui.video_provider }

    bitbag_sylius_cms_plugin.media_provider.file:
        class: App\MediaProvider\GenericProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/file.html.twig"
            - "media/file"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: file, label: bitbag_sylius_cms_plugin.ui.file_provider }

    sylius_invoicing_plugin.generator.invoice_pdf_file:
        class: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        arguments:
            - "@twig"
            - "@knp_snappy.pdf"
            - "@file_locator"
            - "@@SyliusInvoicingPlugin/Invoice/Download/pdf.html.twig"
            - "@@SyliusInvoicingPlugin/Resources/assets/sylius-logo.png"

    Sylius\RefundPlugin\Generator\CreditMemoPdfFileGenerator:
        arguments:
            - "@sylius_refund.repository.credit_memo"
            - "@twig"
            - "@knp_snappy.pdf"
            - "@file_locator"
            - "@@SyliusRefundPlugin/Download/creditMemo.html.twig"
            - "@@SyliusRefundPlugin/Resources/assets/sylius-logo.png"

    sylius.sitemap_renderer.twig_adapter:
        class: SitemapPlugin\Renderer\TwigAdapter
        arguments:
            - "@twig"
            - "%sylius.sitemap_template%"
            - "%sylius.sitemap_absolute_url%"
            - "%sylius.sitemap_hreflang%"

    sylius.sitemap_index_renderer.twig_adapter:
        class: SitemapPlugin\Renderer\TwigAdapter
        arguments:
            - "@twig"
            - "%sylius.sitemap_index_template%"
            - "%sylius.sitemap_absolute_url%"
