services:
    sylius_demo.listener.admin:
        class: AppBundle\EventListener\AdminListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: sylius.admin_user.pre_delete, method: preDelete }
            - { name: kernel.event_listener, event: sylius.admin_user.pre_update, method: preUpdate }

    sylius_demo.listener.channel:
        class: AppBundle\EventListener\ChannelListener
        arguments: ['@session', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request , method: preCreate }

    sylius_demo.listener.user_registration:
        class: AppBundle\EventListener\UserRegistrationListener
        arguments: ['@session', '@sylius.admin_user.token_generator.email_verification', '@router', '@sylius.context.channel', '@translator.default']
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_register , method: addVerificationLink }
